name: weather_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  data_table_2: ^2.5.15
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/H2Caetano.jpg
    